### ISSUE TITLE
Getting message that at least one org should be authenticated

### ISSUE THREAD

**Issue by dkadam77** [RonzGore/sf-schema-explorer#7]
Hello,

I have installed this plugin on Windows and Mac OS and it works on Mac Os but not on Windows.

In VsCode Windows; it shows a message that at least one org should be authenticated. I have reinstalled VSCode as well with plugin but still it does not work. Please see the screen-shot. Can you please look into this?

![image](https://user-images.githubusercontent.com/8331780/87754174-f64def00-c821-11ea-98ac-bef65d1ec73e.png)

**Comment by dkadam77** [comment]
I verified all the JS files and found that internally it was throwing the error -
Command failed: SFDX_JSON_TO_STDOUT=true sfdx force:org:list --json
'SFDX_JSON_TO_STDOUT' is not recognized as an internal or external command,
operable program or batch file.


So I  removed SFDX_JSON_TO_STDOUT=true from all the commands from all the JS files and it worked like charm. I guess use of SFDX_JSON_TO_STDOUT=true is deprecated.

**Comment by thombehrens** [comment]
I am also having this issue.

@dkadam77, can you elaborate here? From which files did you remove references to SFDX_JSON_TO_STDOUT?

I'd be happy to submit a pull request with the needed change once we get it sorted out.

**Comment by RonzGore** [comment]
Hi @dkadam77 Thanks a lot for investigating and looking into the issue. Let me have a look at it and get it fixed.

**Comment by dkadam77** [comment]
Kindly replace all JS files in the location from the attached zip file. I do not remember now which all JS files I changed so replace all the files. This should fix the issue.

C:\Users\XXXXX\.vscode\extensions\rohangore.schema-explorer-0.5.0\out


[Out.zip](https://github.com/RonzGore/sf-schema-explorer/files/4959097/Out.zip)

**Comment by RonzGore** [comment]
Thanks @dkadam77. Fixed this in this PR https://github.com/RonzGore/sf-schema-explorer/pull/9. Please test and let me know if it is working and I will close the issue😎

**Comment by NehaMishraGitHub** [comment]
Hi @dkadam77 , we got a confirmation from another windows user who was facing the same issue. So I am closing out this issue. Feel free to open another one, if/whenever you find any other bug.
Thanks for the help!
